In [2]:
import pandas as pd
from src.utils import EncoderDecoder
import torch
from src.data.datasets import KilterDataset

In [3]:
ds = KilterDataset()

In [4]:
t = ds[0][0]

In [6]:
torch.where(t.long())

(tensor([0, 0, 1, 1, 1, 1, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3]),
 tensor([21, 25,  7, 11, 17, 21, 23,  3,  1,  7, 11, 17, 21, 21, 27, 27]),
 tensor([11, 13, 21, 23, 23, 21, 17, 25, 15, 13, 15, 15,  3,  9,  3,  7]))